version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - '@angular/*'
          - 'angular-eslint'
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
